services:
  - type: web
    name: school-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn school_website.wsgi"

    staticPublishPath: staticfiles
